# Generated by Django 3.0.1 on 2019-12-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='group_title',
            field=models.CharField(default='tst', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authr.UserProfileInfo'),
        ),
    ]
