# Generated by Django 3.0.1 on 2019-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authr', '0002_auto_20191231_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='group_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
